name: canton_design_system
description: Canton Design System elements.
version: 0.0.1
author: Carlton Aikins
homepage: null
publish_to: "none"

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_page_transition: 
  flutter_riverpod:
  flutter_slidable:
  flutter_feather_icons:
  flutter_spinkit:
  emojis:
  circular_check_box:
  liquid_pull_to_refresh:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  fonts:
    - family: CantonIconsBold
      fonts:
        - asset: fonts/CantonIconsBold.ttf
    - family: CantonIconsLine
      fonts:
        - asset: fonts/CantonIconsLine.ttf
    - family: Icons_curved
      fonts:
        - asset: fonts/Icons_curved.ttf
    - family: Butler
      fonts:
        - asset: fonts/Butler-Bold.otf
          weight: 800
        - asset: fonts/Butler-Medium.otf
          weight: 600
        - asset: fonts/Butler-Regular.otf
          weight: 400
    - family: Inter
      fonts:
        - asset: fonts/Inter-Bold.otf
          weight: 800
        - asset: fonts/Inter-BoldItalic.otf
          weight: 800
          style: italic
        - asset: fonts/Inter-SemiBold.otf
          weight: 600
        - asset: fonts/Inter-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/Inter-Medium.otf
          weight: 500
        - asset: fonts/Inter-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/Inter-Regular.otf
          weight: 400
        - asset: fonts/Inter-Italic.otf
          weight: 400
          style: italic

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
